[package]
name        = "ferogram-py"
version     = "0.5.2"
edition     = "2024"
description = "Python MTProto client based on ferogram (Rust MTProto)"
build       = "build.rs"
license     = "MIT OR Apache-2.0"

[lib]
name       = "_ferogram"
crate-type = ["cdylib"]

[dependencies]
ferogram-mtsender   = { git = "https://github.com/ankit-chaubey/ferogram", rev = "f747bf418da2f8d9f6288cc5aa56875034c112f9" }
ferogram-session    = { git = "https://github.com/ankit-chaubey/ferogram", rev = "f747bf418da2f8d9f6288cc5aa56875034c112f9", features = ["sqlite-session", "libsql-session"] }
ferogram-connect    = { git = "https://github.com/ankit-chaubey/ferogram", rev = "f747bf418da2f8d9f6288cc5aa56875034c112f9" }
ferogram-tl-types   = { git = "https://github.com/ankit-chaubey/ferogram", rev = "f747bf418da2f8d9f6288cc5aa56875034c112f9" }
ferogram-crypto     = { git = "https://github.com/ankit-chaubey/ferogram", rev = "f747bf418da2f8d9f6288cc5aa56875034c112f9" }
getrandom           = "0.2"
base64              = "0.22"
pyo3                = { version = "0.24", features = ["extension-module", "abi3-py39"] }
pyo3-async-runtimes = { version = "0.24", features = ["tokio-runtime"] }
tokio               = { version = "1", features = ["full"] }

[profile.release]
strip     = true
opt-level = 3
lto       = true

[build-dependencies]
pyo3-build-config = "0.24"
