[package]
name        = "ferogram-py"
version     = "0.5.0"
edition     = "2024"
description = "Python bindings for ferogram (Rust MTProto)"
license     = "MIT OR Apache-2.0"

[lib]
name       = "_ferogram"
crate-type = ["cdylib"]

[dependencies]
ferogram-mtsender   = { git = "https://github.com/ankit-chaubey/ferogram", rev = "8c9e00db5db284a4a5993ddbe7a90c4f13810ce9" }
ferogram-session    = { git = "https://github.com/ankit-chaubey/ferogram", rev = "8c9e00db5db284a4a5993ddbe7a90c4f13810ce9", features = ["sqlite-session", "libsql-session"] }
ferogram-connect    = { git = "https://github.com/ankit-chaubey/ferogram", rev = "8c9e00db5db284a4a5993ddbe7a90c4f13810ce9" }
ferogram-tl-types   = { git = "https://github.com/ankit-chaubey/ferogram", rev = "8c9e00db5db284a4a5993ddbe7a90c4f13810ce9" }
ferogram-crypto     = { git = "https://github.com/ankit-chaubey/ferogram", rev = "8c9e00db5db284a4a5993ddbe7a90c4f13810ce9" }
getrandom           = "0.2"
base64              = "0.22"
pyo3                = { version = "0.24", features = ["extension-module", "abi3-py39"] }
pyo3-async-runtimes = { version = "0.24", features = ["tokio-runtime"] }
tokio               = { version = "1", features = ["full"] }

[profile.release]
strip     = true
opt-level = 3
lto       = true
