[build-system]
requires      = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name        = "ferogram"
version     = "0.2.3"
description = "Python wrapper for ferogram, blazing-fast Rust MTProto library for Telegram."
readme      = "README.md"
license     = { text = "MIT OR Apache-2.0" }
authors     = [{ name = "Ankit Chaubey", email = "ankitchaubey.dev@gmail.com" }]
keywords    = ["telegram", "mtproto", "rust", "client", "bot", "ferogram"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
    "Topic :: Communications :: Chat",
    "Topic :: Software Development :: Libraries",
]
requires-python = ">=3.9"

[project.urls]
Homepage      = "https://github.com/ankit-chaubey/ferogram-py"
Source        = "https://github.com/ankit-chaubey/ferogram-py"
Documentation = "https://github.com/ankit-chaubey/ferogram-py#readme"
Tracker       = "https://github.com/ankit-chaubey/ferogram-py/issues"
Author        = "https://github.com/ankit-chaubey"

[tool.maturin]
module-name   = "ferogram._ferogram"
features      = ["pyo3/extension-module"]
