[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ferogram"
version = "0.0.0"
description = "Python wrapper for ferogram a blazing-fast Rust MTProto library for Telegram clients and bots."
readme = "README.md"
license = { text = "MIT OR Apache-2.0" }
authors = [
    { name = "Ankit Chaubey", email = "ankitchaubey.dev@gmail.com" }
]
keywords = ["telegram", "mtproto", "rust", "client", "bot"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
    "Topic :: Communications :: Chat",
    "Topic :: Software Development :: Libraries",
]
requires-python = ">=3.9"

[project.urls]
Homepage   = "https://github.com/ankit-chaubey/ferogram"
Repository = "https://github.com/ankit-chaubey/ferogram"
