"""Example: Telegram rich message feature verify/replace placeholder before running."""

import asyncio
import ferogram

API_ID = 0
API_HASH = ""
BOT_TOKEN = ""
CHAT = "@your_chat"


async def main():
    client = ferogram.Client("rich_bot", api_id=API_ID, api_hash=API_HASH)
    await client.start(bot_token=BOT_TOKEN)

    #  Inline entities via plain send_message (parse_mode path)
    await client.send_message(CHAT, "**bold** _italic_ `code` ~~strike~~ ||spoiler||",
                              parse_mode="markdown")
    await client.send_message(CHAT, '<b>bold</b> <i>italic</i> <tg-spoiler>secret</tg-spoiler>',
                              parse_mode="html")

    #  Full rich message: headings, lists, table, blockquote, code, math
    await client.send_rich_message(CHAT, """
# Ferogram Rich Message Demo

## Features

- **Bold**, _italic_, ~~strikethrough~~, `inline code`
- ||Spoiler text|| and ==also spoiler==
- [Link](https://t.me/) and [email](mailto:a@b.com)

## Ordered list

1. First item
2. Second item
3. Third item

## Task list

- [x] Implemented inline entities
- [x] Implemented rich message blocks
- [ ] Deploy to production

## Table

| Feature       | HTML  | Markdown |
|:--------------|:-----:|:--------:|
| Headings      | yes   | yes      |
| Tables        | yes   | yes      |
| Block math    | yes   | yes      |
| Media blocks  | yes   | yes      |

## Code block

```python
async def greet(client, peer):
    await client.send_rich_message(peer, "# Hello!")
```

## Block math

$$E = mc^2$$

```math
\\int_0^\\infty e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}
```

## Blockquote

> Block quotation started
>
> Block quotation continued
>
> The last line of the block quotation

---

## Footnotes

Text with a reference[^ref1] and another[^ref2].

[^ref1]: Definition of the first footnote.
[^ref2]: Definition of the second footnote.

## Collapsible details

<details open><summary>Summary with **bold text**</summary>

### Inside details heading

- List item with _italic_
- Another item with `code`

</details>

## Pull quote

<aside>The best way to predict the future is to invent it.<cite>Alan Kay</cite></aside>

## Footer

<footer>Generated by ferogram-py rich message support</footer>
""", mode="markdown")

    #  Rich HTML
    await client.send_rich_message(CHAT, """
<h1>HTML Rich Message</h1>
<p>Paragraph with <b>bold</b>, <i>italic</i>, <u>underline</u>, <sub>sub</sub>, <sup>sup</sup>.</p>
<p><mark>highlighted</mark> and <tg-spoiler>spoiler</tg-spoiler> and <tg-math>x^2 + y^2</tg-math>.</p>

<h2>Ordered list with options</h2>
<ol start="3" type="a">
  <li>Item starting at c</li>
  <li>Item d</li>
</ol>

<h2>Blockquote with credit</h2>
<blockquote>Simplicity is the ultimate sophistication.<cite>Leonardo da Vinci</cite></blockquote>

<h2>Table with borders</h2>
<table bordered striped>
  <caption>Sample table</caption>
  <tr><th>Name</th><th>Value</th></tr>
  <tr><td>Speed</td><td align="right">42 ms</td></tr>
  <tr><td>Status</td><td><tg-spoiler>ready</tg-spoiler></td></tr>
</table>

<h2>Block math</h2>
<tg-math-block>E = mc^2</tg-math-block>

<h2>Anchor navigation</h2>
<a name="chapter-1"></a>
<p>See <a href="#chapter-1">chapter 1</a> for details.</p>

<h2>Details block</h2>
<details open>
  <summary>Expandable content</summary>
  <p>This content is shown by default because <code>open</code> is set.</p>
  <ul><li>Nested list item 1</li><li>Nested list item 2</li></ul>
</details>

<footer>HTML rich message footer</footer>
""", mode="html")

    #  Media blocks (URL-based, no upload needed for public URLs)
    await client.send_rich_message(CHAT, """
# Media blocks

![](https://telegram.org/example/photo.jpg "Photo caption")
![](https://telegram.org/example/video.mp4 "Video caption")
![](https://telegram.org/example/audio.mp3 "Audio caption")

## Collage

<tg-collage>
![](https://telegram.org/example/photo.jpg)
![](https://telegram.org/example/video.mp4)
</tg-collage>

## Slideshow

<tg-slideshow>
![](https://telegram.org/example/photo.jpg)
![](https://telegram.org/example/video.mp4)
</tg-slideshow>
""", mode="markdown")

    #  Map block
    await client.send_rich_message(CHAT,
        '<tg-map lat="41.9" long="12.5" zoom="14"/>'
        '<figure><tg-map lat="41.9" long="12.5" zoom="14"/>'
        '<figcaption>Rome, Italy<cite>OpenStreetMap</cite></figcaption></figure>',
        mode="html")

    #  Streaming draft then finalise
    draft_id = 1
    for partial in ["# Generating...", "# Generating...\n\nStep 1 done.", "# Final\n\nAll steps done."]:
        await client.send_rich_message_draft(CHAT, partial, draft_id=draft_id)
        await asyncio.sleep(1)
    await client.send_rich_message(CHAT, "# Final\n\nAll steps done.")

    #  Fetch rendered rich message tree
    msg = await client.send_rich_message(CHAT, "# Fetch test\n\nThis is fetchable.")
    msg_id = msg.get("id") or msg.get("updates", [{}])[0].get("id", 0)
    if msg_id:
        tree = await client.get_rich_message(CHAT, msg_id)
        print("RichMessage blocks:", len(tree.get("blocks", [])))

    await client.stop()


if __name__ == "__main__":
    asyncio.run(main())
